### ISSUE TITLE
Bump build tools version to 14.39

### ISSUE THREAD

**Issue by FaustinCarter** [conda-forge/vc-feedstock#73] opened 2024-03-08 23:51 UTC
### Comment:

The latest build tools version is 14.39, and that does not yet exist on conda-forge, which means anyone using a bleeding edge install of VS2022 is out of luck without some extra leg work.

**Comment by traversaro** [comment] 2024-03-20 15:14
@FaustinCarter  In theory this should have been handled by https://github.com/conda-forge/vc-feedstock/pull/56, can you report your `conda list` in the environment you are experiencing the problem? This is also valid for other person experiencing the same problem @S-Dafarra @dariosortino .

**Comment by S-Dafarra** [comment] 2024-03-20 15:18
> @FaustinCarter In theory this should have been handled by #56, can you report your `conda list` in the environment you are experiencing the problem? This is also valid for other person experiencing the same problem @S-Dafarra @dariosortino.

Here the 
<details> 
<summary><code>mamba list</code></summary>

```
(robsub) C:\Software>mamba list
# packages in environment at C:\Software\mambaforge\envs\robsub:
#
# Name                    Version                   Build  Channel
ace                       7.1.2                h63175ca_0    conda-forge
aiohttp                   3.9.1           py312he70551f_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
aom                       3.7.1                h63175ca_0    conda-forge
asio                      1.29.0               h63175ca_0    conda-forge
assimp                    5.3.1                h81f0834_2    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
blosc                     1.21.5               hdccc3a2_0    conda-forge
boost                     1.82.0               hd42ba9a_6    conda-forge
brotli                    1.0.9                hcfcfb64_9    conda-forge
brotli-bin                1.0.9                hcfcfb64_9    conda-forge
bullet-cpp                3.25                 h2ab9e98_2    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
c-ares                    1.25.0               hcfcfb64_0    conda-forge
c-compiler                1.7.0                hcfcfb64_0    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cfitsio                   4.3.0                h9b0cee5_0    conda-forge
clangdev                  5.0.0                   flang_3    conda-forge
cmake                     3.28.1               hf0feee3_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
compilers                 1.7.0                h57928b3_0    conda-forge
console_bridge            1.0.2                h5362a0b_1    conda-forge
contourpy                 1.2.0           py312h0d7def4_0    conda-forge
cppzmq                    4.10.0               h42135b4_1    conda-forge
cxx-compiler              1.7.0                h91493d7_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dartsim                   6.13.1               haebf736_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dirent                    1.21                          0    conda-forge
dlfcn-win32               1.3.0                h0e60522_0    conda-forge
double-conversion         3.3.0                h63175ca_0    conda-forge
eigen                     3.4.0                h91493d7_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fcl                       0.7.0                he22821c_4    conda-forge
ffmpeg                    6.1.0           gpl_h8ec0088_102    conda-forge
flang                     5.0.0           he025d50_20180525    conda-forge
flang_win-64              5.0.0           h13ae965_20180526    conda-forge
flann                     1.9.2                h23e6bae_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.47.0          py312he70551f_0    conda-forge
fortran-compiler          1.7.0                h9655429_0    conda-forge
freeglut                  3.2.2                h63175ca_2    conda-forge
freeimage                 3.18.0              h609497f_18    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
frozenlist                1.4.1           py312he70551f_0    conda-forge
gazebo                    11.14.0              h649ee58_3    conda-forge
geos                      3.12.0               h1537add_0    conda-forge
geotiff                   1.7.1               hcf4a93f_14    conda-forge
getopt-win32              0.1                  hcfcfb64_1    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
glfw                      3.3.9                hcfcfb64_0    conda-forge
glib                      2.78.1               h12be248_0    conda-forge
glib-networking           2.78.0               h8365e19_0    conda-forge
glib-tools                2.78.1               h12be248_0    conda-forge
glm                       0.9.9.8              h181d51b_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  8.1.0                h51cb2cd_0    conda-forge
gsl                       2.7                  hdfb1a43_0    conda-forge
gst-plugins-bad           1.22.6               ha2afc39_0    conda-forge
gst-plugins-base          1.22.7               h001b923_0    conda-forge
gst-plugins-good          1.22.7               hdc28085_0    conda-forge
gstreamer                 1.22.7               hb4038d2_0    conda-forge
gts                       0.7.6                h6b5321d_4    conda-forge
h5py                      3.10.0          nompi_py312h1751c5b_101    conda-forge
harfbuzz                  8.3.0                h7ab893a_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h73e8ff5_100    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imath                     3.1.9                h12be248_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
ipopt                     3.14.13              ha9547d1_0    conda-forge
ipython                   8.20.0             pyh7428d3b_0    conda-forge
irrlicht                  1.8.5                h65f4d7e_4    conda-forge
jasper                    4.1.1                h28f2b1a_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jxrlib                    1.1                  hcfcfb64_3    conda-forge
kealib                    1.5.3                hd248416_0    conda-forge
khronos-opencl-icd-loader 2023.04.17           h64bf75a_0    conda-forge
kiwisolver                1.4.5           py312h0d7def4_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lame                      3.100             hcfcfb64_1003    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20230802.1      cxx17_h63175ca_0    conda-forge
libaec                    1.1.2                h63175ca_1    conda-forge
libarchive                3.7.2                h6f8411a_0    conda-forge
libblas                   3.9.0              20_win64_mkl    conda-forge
libboost                  1.82.0               h65993cd_6    conda-forge
libboost-devel            1.82.0               h91493d7_6    conda-forge
libboost-headers          1.82.0               h57928b3_6    conda-forge
libboost-python           1.82.0          py312h4f1204c_6    conda-forge
libboost-python-devel     1.82.0          py312hd42ba9a_6    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_9    conda-forge
libbrotlidec              1.0.9                hcfcfb64_9    conda-forge
libbrotlienc              1.0.9                hcfcfb64_9    conda-forge
libcblas                  3.9.0              20_win64_mkl    conda-forge
libccd-double             2.1                  h63175ca_3    conda-forge
libclang                  15.0.7          default_h77d9078_3    conda-forge
libclang13                15.0.7          default_h77d9078_3    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.5.0                hd5e4a3a_0    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflac                   1.4.3                h63175ca_0    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgd                     2.3.3                h312136b_9    conda-forge
libgdal                   3.8.0                h803bde4_2    conda-forge
libglib                   2.78.1               he8f3873_0    conda-forge
libgoogle-cloud           2.12.0               h39f2fc6_4    conda-forge
libgrpc                   1.59.3               h5bbd4a7_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libignition-cmake2        2.16.0               h63175ca_1    conda-forge
libignition-common3       3.15.1               hc1f3b3c_2    conda-forge
libignition-fuel-tools4   4.6.0                hacc15eb_5    conda-forge
libignition-math6         6.15.1          py312haf63811_1    conda-forge
libignition-msgs5         5.11.0               hf2928cc_4    conda-forge
libignition-tools1        1.5.0                hf5993cb_3    conda-forge
libignition-transport8    8.4.0                hbed1618_7    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             haf3e7a6_1018    conda-forge
liblapack                 3.9.0              20_win64_mkl    conda-forge
liblapacke                3.9.0              20_win64_mkl    conda-forge
libmatio                  1.5.26               h8f40fab_0    conda-forge
libnetcdf                 4.9.2           nompi_h8284064_112    conda-forge
libode                    0.16.2              h53d5487_12    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopenblas               0.3.25          pthreads_hc140b1d_0    conda-forge
libopencv                 4.8.1           py312h601028a_5    conda-forge
libopenvino               2023.1.0             h63175ca_2    conda-forge
libopenvino-auto-batch-plugin 2023.1.0             h63175ca_2    conda-forge
libopenvino-auto-plugin   2023.1.0             h63175ca_2    conda-forge
libopenvino-hetero-plugin 2023.1.0             h63175ca_2    conda-forge
libopenvino-intel-cpu-plugin 2023.1.0             h63175ca_2    conda-forge
libopenvino-intel-gpu-plugin 2023.1.0             h63175ca_2    conda-forge
libopenvino-ir-frontend   2023.1.0             h63175ca_2    conda-forge
libopenvino-onnx-frontend 2023.1.0             h63175ca_2    conda-forge
libopenvino-paddle-frontend 2023.1.0             h63175ca_2    conda-forge
libopenvino-pytorch-frontend 2023.1.0             h63175ca_2    conda-forge
libopenvino-tensorflow-frontend 2023.1.0             h63175ca_2    conda-forge
libopenvino-tensorflow-lite-frontend 2023.1.0             h63175ca_2    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     16.1                 hdb24f17_7    conda-forge
libprotobuf               4.24.4               hb8276f3_0    conda-forge
libpsl                    0.21.2               hcfd4269_1    conda-forge
libraw                    0.21.1               h5557f11_2    conda-forge
libre2-11                 2023.06.02           h8c5ae5e_0    conda-forge
librttopo                 1.1.0               h92c5fdb_14    conda-forge
libsdformat               9.8.0                h5ba8b87_5    conda-forge
libsndfile                1.2.2                h81429f1_1    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsoup                   2.74.3               hef79ac6_1    conda-forge
libspatialite             5.1.0                hbf340bc_1    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libusb                    1.0.26             h8ffe710_100    conda-forge
libuv                     1.44.2               hcfcfb64_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.11.6               hc3477c8_0    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
loguru                    0.7.2           py312h2e8e312_1    conda-forge
lua                       5.4.6                h57928b3_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
make                      4.3                  h3d2af85_1    conda-forge
matplotlib                3.8.2           py312h2e8e312_0    conda-forge
matplotlib-base           3.8.2           py312h26ecaf7_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
metis                     5.1.1                h63175ca_2    conda-forge
minizip                   4.0.4                h5bed578_0    conda-forge
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mpg123                    1.32.3               h63175ca_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.4           py312he70551f_1    conda-forge
mumps-seq                 5.2.1               h1f49738_14    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ninja                     1.11.1               h91493d7_0    conda-forge
nlohmann_json             3.11.2               h39d44d4_0    conda-forge
numpy                     1.26.3          py312h8753938_0    conda-forge
octomap                   1.9.8                h91493d7_0    conda-forge
ogre                      1.10.12             hc646683_16    conda-forge
openal-soft               1.22.2               h91493d7_0    conda-forge
openblas                  0.3.25          pthreads_h3721920_0    conda-forge
opencv                    4.8.1           py312h63a316d_5    conda-forge
openexr                   3.2.1                h5fba010_0    conda-forge
openh264                  2.4.0                h63175ca_0    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pango                     1.50.14              h07c897b_2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcl                       1.13.1               ha569048_3    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.2.0          py312he768995_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.43.0               h63175ca_0    conda-forge
pkg-config                0.29.2            h2bf4dc2_1008    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   23.11.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
portaudio                 19.6.0               h63175ca_9    conda-forge
postgresql                16.1                 hc80876b_7    conda-forge
proj                      9.3.0                he13c7e8_2    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pugixml                   1.14                 h63175ca_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-opencv                 4.8.1           py312hc50e9f6_5    conda-forge
pybind11                  2.11.1          py312h0d7def4_2    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pybind11-global           2.11.1          py312h0d7def4_2    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py312he09f080_5    conda-forge
pyqt5-sip                 12.12.2         py312h53d5487_5    conda-forge
python                    3.12.1          h2628c8c_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pyzmq                     25.1.2          py312h1ac6f91_0    conda-forge
qhull                     2020.2               h70d2c02_2    conda-forge
qt-main                   5.15.8              h9e85ed6_17    conda-forge
qwt                       6.2.0                h07be427_6    conda-forge
re2                       2023.06.02           hcbb65ff_0    conda-forge
ruby                      3.2.2                h20ad4f3_1    conda-forge
sdl                       1.2.68               h21dd15a_0    conda-forge
sdl2                      2.28.5               h63175ca_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
simbody                   3.7                  hade3207_3    conda-forge
sip                       6.7.12          py312h53d5487_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
soxr                      0.1.3                hcfcfb64_3    conda-forge
spdlog                    1.12.0               h64d2f7d_2    conda-forge
sqlite                    3.44.2               hcfcfb64_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
svt-av1                   1.7.0                h63175ca_0    conda-forge
swig                      4.1.0                h9eeddcc_4    conda-forge
tbb                       2021.11.0            h91493d7_0    conda-forge
tbb-devel                 2021.11.0            h91493d7_0    conda-forge
tiledb                    2.16.3               hbf04793_3    conda-forge
tiny-process-library      2.0.4                h63175ca_1    conda-forge
tinyxml                   2.6.2                h2d74725_2    conda-forge
tinyxml2                  9.0.0                h0e60522_2    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlplusplus              3.3.0                h63175ca_0    conda-forge
tornado                   6.3.3           py312he70551f_1    conda-forge
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
u-msgpack-python          2.8.0              pyhd8ed1ab_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urdfdom                   3.1.1                h33150cf_0    conda-forge
urdfdom_headers           1.1.1                h91493d7_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
utfcpp                    4.0.5                h57928b3_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
vs2019_win-64             19.29.30139         he1865b1_18    conda-forge
vs2022_win-64             19.38.33130         h0bfb142_18    conda-forge
vswhere                   3.1.4                h57928b3_0    conda-forge
vtk                       9.2.6           qt_py312h1234567_219    conda-forge
vtk-base                  9.2.6           qt_py312h1234567_219    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win32_setctime            1.1.0              pyhd8ed1ab_0    conda-forge
wslink                    1.12.4             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xerces-c                  3.2.5                h63175ca_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.1.1                hcd874cb_0    conda-forge
xorg-libsm                1.2.4                hcd874cb_0    conda-forge
xorg-libx11               1.8.7                hefa74cf_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.17               hcd874cb_0    conda-forge
xorg-libxt                1.3.0                hcd874cb_1    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yarl                      1.9.3           py312he70551f_0    conda-forge
zeromq                    4.3.5                h63175ca_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
zziplib                   0.13.69              h1d00b33_1    conda-forge
```

</details>

**Comment by traversaro** [comment] 2024-03-22 08:37
I just tested on my machine, and even if I see the messages:
~~~
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.9.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[ERROR:vcvars.bat] Toolset directory for version '14.38' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.9.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
~~~

at the end of activation script, then I am able to build fine CMake projects using ninja. What I guess is happening, is that the failure is coming from the invocation of https://github.com/conda-forge/vc-feedstock/blob/8725d3429b35eb8b12897a015925ef4d2a135edc/recipe/activate.bat#L135 . However, that line fails, but then the environment is anyhow activated by the line https://github.com/conda-forge/vc-feedstock/blob/8725d3429b35eb8b12897a015925ef4d2a135edc/recipe/activate.bat#L141 .

<details>

<summary>This is my `mamba list`</summary>

~~~
(idyntreedev) C:\src\idyntree\buildninja>mamba list
# packages in environment at C:\Users\straversaro\AppData\Local\miniforge3\envs\idyntreedev:
#
# Name                    Version                   Build  Channel
assimp                    5.3.1                h81f0834_2    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cmake                     3.28.3               hf0feee3_0    conda-forge
eigen                     3.4.0                h91493d7_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
libboost                  1.82.0               h65993cd_6    conda-forge
libcurl                   8.6.0                hd5e4a3a_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.80.0               h39d0aa6_0    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libuv                     1.48.0               hcfcfb64_0    conda-forge
libxml2                   2.12.6               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
make                      4.3                  h3d2af85_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
ninja                     1.11.1               h91493d7_0    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pkg-config                0.29.2            h2bf4dc2_1008    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
vs2022_win-64             19.38.33130         h0bfb142_18    conda-forge
vswhere                   3.1.4                h57928b3_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
~~~

</details>

@S-Dafarra @FaustinCarter @dariosortino TL;DR: I tested and at least in my case the problem is just the confusing activation message. Are you experiencing some other failure if you try to build something in the environment?

**Comment by S-Dafarra** [comment] 2024-03-22 09:12
> Are you experiencing some other failure if you try to build something in the environment?

No particular failure from my side, I just noticed that ``intellisense`` of Visual Studio was not working properly with the standard library includes.

**Comment by traversaro** [comment] 2024-03-22 09:19
> > Are you experiencing some other failure if you try to build something in the environment?
> 
> No particular failure from my side, I just noticed that `intellisense` of Visual Studio was not working properly with the standard library includes.

Interesting, if you want to spend time on this it would be interesting to see the diff between `set` after you activate your `env` , and `set` after you manually call `call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"` to fix intellisense.

**Comment by dariosortino** [comment] 2024-03-22 14:24
> > Are you experiencing some other failure if you try to build something in the environment?
> 
> No particular failure from my side, I just noticed that `intellisense` of Visual Studio was not working properly with the standard library includes.

I just upgraded Visual Studio to its newer version, then generate again the CMakeCache. It fixed my broken Intellisense

**Comment by S-Dafarra** [comment] 2024-03-22 18:26
> Interesting, if you want to spend time on this it would be interesting to see the diff between `set` after you activate your `env` , and `set` after you manually call `call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"` to fix intellisense.

I checked and it seems that with the package installed, actually there are more paths set with respect to the manual case. At this point, I am not entirely sure it is an issue anymore. I will double-check in the following days if I manage to isolate some macroscopic differences.

**Comment by FaustinCarter** [comment] 2024-03-25 20:41
> @FaustinCarter In theory this should have been handled by #56, can you report your `conda list` in the environment you are experiencing the problem? This is also valid for other person experiencing the same problem @S-Dafarra @dariosortino .

@traversaro Here's what conda-build was sticking in the build env:

```
    bzip2:           1.0.8-hcfcfb64_5         
    ca-certificates: 2024.2.2-h56e8100_0      
    eigen:           3.4.0-h91493d7_0         
    libffi:          3.4.2-h8ffe710_5         
    libsqlite:       3.45.2-hcfcfb64_0        
    libzlib:         1.2.13-hcfcfb64_5        
    openssl:         3.2.1-hcfcfb64_1         
    pip:             24.0-pyhd8ed1ab_0        
    pybind11:        2.11.1-py38hb1fd069_2    
    pybind11-global: 2.11.1-py38hb1fd069_2    
    python:          3.8.19-h4de0772_0_cpython
    python_abi:      3.8-4_cp38               
    setuptools:      69.2.0-pyhd8ed1ab_0      
    tk:              8.6.13-h5226925_1        
    ucrt:            10.0.22621.0-h57928b3_0  
    vc:              14.3-hcf57466_18         
    vc14_runtime:    14.38.33130-h82b7239_18  
    vs2015_runtime:  14.38.33130-hcb4865c_18  
    vs2022_win-64:   19.34.31933-h78da3e3_17  
    vswhere:         3.1.4-h57928b3_0         
    wheel:           0.43.0-pyhd8ed1ab_0      
    xz:              5.2.6-h8d14728_0  
```

**Comment by mgovers** [comment] 2024-05-17 06:56
The default image changed MSVC version to 14.39. Seems similar to #70 and #68 .

What's the reason for explicitly pinning to a single version instead of using the default toolchain? It is available and is actually logged by the build script (see e.g. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=935910&view=logs&j=270c184a-5340-5429-138e-d97b868f5bb8&t=e13479c6-59fe-5ccc-f20c-19bfb689de0c&l=953 ):

```bat
%SRC_DIR%>type "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt" 
14.39.33519
```

Only a couple lines later, the pinned version is requested, which then produces incorrect output (see e.g. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=935910&view=logs&j=270c184a-5340-5429-138e-d97b868f5bb8&t=e13479c6-59fe-5ccc-f20c-19bfb689de0c&l=984 ):

```bat
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.38 10.0.22621.0 
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.9.7
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[ERROR:vcvars.bat] Toolset directory for version '14.38' was not found.
```

**Comment by isuruf** [comment] 2024-05-20 21:35
Fixed now

**Closed by isuruf** 2024-05-20 21:35 UTC
Labels: question
